export const users = [
  {
    id: 1,
    name: "Arielle",
    date: "1/20/2023",
    email: "aproffitt0@tripadvisor.com",
    gender: "Female",
  },
  {
    id: 2,
    name: "Cleveland",
    date: "11/8/2022",
    email: "csweetmore1@issuu.com",
    gender: "Male",
  },
  {
    id: 3,
    name: "Ania",
    date: "7/9/2023",
    email: "averdie2@netvibes.com",
    gender: "Female",
  },
  {
    id: 4,
    name: "Kain",
    date: "1/20/2023",
    email: "karran3@qq.com",
    gender: "Male",
  },
  {
    id: 5,
    name: "Craggy",
    date: "10/13/2022",
    email: "cskerman4@flickr.com",
    gender: "Male",
  },
  {
    id: 6,
    name: "Cathryn",
    date: "11/17/2022",
    email: "cknightsbridge5@unblog.fr",
    gender: "Female",
  },
  {
    id: 7,
    name: "Dan",
    date: "2/1/2023",
    email: "dpollen6@yahoo.com",
    gender: "Male",
  },
  {
    id: 8,
    name: "Claudetta",
    date: "7/27/2022",
    email: "ccurcher7@furl.net",
    gender: "Female",
  },
  {
    id: 9,
    name: "Vernen",
    date: "9/17/2022",
    email: "vgooddie8@acquirethisname.com",
    gender: "Male",
  },
  {
    id: 10,
    name: "Lowe",
    date: "11/22/2022",
    email: "lfrancois9@yahoo.co.jp",
    gender: "Male",
  },
];
